//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASH.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobTrackings = new HashSet<JobTracking>();
        }
    
        public long JobNumber { get; set; }
        public Nullable<int> status { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<JobTracking> JobTrackings { get; set; }
    }
}
